### PR TITLE
 [13.0][MIG] privacy_consent

### PR DESCRIPTION
**Pull request by techultrasolutions**
Privacy - Consent
=================
This module allows the user to define a set of subjects (partners)
affected by any data processing activity, and establish
a process to ask them for consent to include them in that activity.

For those that need explicit consent as a lawfulness base for personal data
processing, as required by GDPR (article 6.1.a), this module provides the
needed tools to automate it.

### CODE REVIEW

**Comment by techultrasolutions** [comment]
Depends on #43

**Comment by treylade** [comment]
I would really love to use this module. Any ideas on how soon this could be migrated to v13, @techultrasolutions? 
Since the dependent module "privacy" looks like its shortly to be released?
Thank you for your work!

**Comment by techultrasolutions** [comment]
> I would really love to use this module. Any ideas on how soon this could be migrated to v13, @techultrasolutions?
> Since the dependent module "privacy" looks like its shortly to be released?
> Thank you for your work!

Thank for the appreciation.
We are trying our best. Expect this module in next week but depends on approval. 
Cheers.

**Comment by yajo** [comment]
You're gonna kill me... it happened again.

I was going to open a PR and I suddenly realized I pushed to OCA 13.0 branch. Well, the good part is that the module is migrated already at ce673246d4a1091b9a279488f1b3ef048e5c0c3e. The bad one is that I got hit by https://github.com/OCA/odoo-module-migrator/pull/47 yet again and we had no review again.

Sorry... closing.

**Pull request closed without merging**
