### PR TITLE
14.0 mig privacy

### PR DESCRIPTION
**Pull request by valtterilattu**

### CODE REVIEW

**Review by jarmokortetjarvi — APPROVED** [review]
LGTM.

There are no actual changes between `13.0` and `14.0`
https://github.com/OCA/data-protection/compare/13.0...valtterilattu:14.0-mig-privacy

**Comment by victoralmau** [comment]
Please add this change https://github.com/OCA/data-protection/pull/59 which is already in v13.

**Comment by lamtritin90** [comment]
> Please add this change #59 which is already in v13.

Would be ready to be merged after applying this change.

**Comment by victoralmau** [comment]
> > Please add this change #59 which is already in v13.
> 
> Would be ready to be merged after applying this change.

When this change is applied I will be able to approve it.

**Comment by victoralmau** [comment]
Superseed by: https://github.com/OCA/data-protection/pull/60

**Review by dreispt — APPROVED** [review]

**Comment by dreispt** [comment]
Superseded by #60

**Pull request closed without merging**
