### PR TITLE
[16.0][MIG] Migrate data-protection to 16.0

### PR DESCRIPTION
**Pull request by tde-banana-odoo**
I don't know what I am doing.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
We only migrate one module per pull request. And please read the procedure carefully with the environment variables for extracting correctly the commit history.

**Comment by tde-banana-odoo** [comment]
Should I make specific commits for each module then ? Or do you prefer two PRs ? Because as privacy_content is based on privacy, makes sense to migrate both of them at the same time in order to test the feature, isn't it ?

**Comment by pedrobaeza** [comment]
We make 2 pull requests, one per module, as each of them have their own commit history. The second one won't be usable (but code reviewable) until the first one is merged and the second rebased on top. I know this approach seems weird, but it's the way to:

- Avoid masking errors on one module through the overlap of dependent modules.
- Promote good unit tests.
- Reduce the scope of the PR to be easily reviewable.

**Comment by tde-banana-odoo** [comment]
Ok :) when in rome, do as the romans do !

**Comment by tde-banana-odoo** [comment]
Created https://github.com/OCA/data-protection/pull/70 for privacy, and https://github.com/OCA/data-protection/pull/71 for privacy_content (currently based on privacy migration, rebase will drop extra commits).

I close this one then :)

**Pull request closed without merging**
