### PR TITLE
[14.0][MIG] privacy: Migration to 14.0

### PR DESCRIPTION
**Pull request by victoralmau**
Superseed: https://github.com/OCA/data-protection/pull/55

Migration to 14.0

Please @Yajo and @joao-p-marques can you review it?

@Tecnativa TT31809

### CODE REVIEW

**Review by joao-p-marques — APPROVED** [review]
Code review :+1:

**Review by yajo — APPROVED** [review]
Code and functional review.

**Comment by pedrobaeza** [comment]
Let's see if both commands work well together:

/ocabot migration privacy

/ocabot merge nobump

**Comment by pedrobaeza** [comment]
Yes, they work, but 2 merges have been launched. I abort mine.

**Comment by pedrobaeza** [comment]
Another edge in the ocabot script if there's no module list in the issue. Added manually one entry and

/ocabot migration privacy

**Comment by yajo** [comment]
What does that command do?

**Comment by pedrobaeza** [comment]
https://github.com/OCA/oca-github-bot/pull/97

**Pull request merged**
