### PR TITLE
Checkin ITIS Odoo 12 GDPDR Modules

### PR DESCRIPTION
**Pull request by ITISAG**

### CODE REVIEW

**Comment by ITISAG** [comment]
The Modules availible for Odoo 11 ported to Odoo 12.

**Comment by etobella** [comment]
@ITISAG Can you review travis, preserve commits and make one PR for each module please?

For the migration, you should follow https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0

**Comment by ITISAG** [comment]
Dear BOT 

IT IS has signed as a company CLA, so please refrain buggin us with nonsense. Otherwise we won't contribute and sponsor! 



@ "Enric Tobella" <notifications@github.com> 


Please give us a call tomorow afternoon and / or point towards the mentioned topics which you have concerns about. Of cause we have done the portation according to the migration guide v11 to 12. 


BR, Joe 




----- Ursprüngliche Mail -----

Von: "OCA CLA BOT" <notifications@github.com> 
An: "OCA/data-protection" <data-protection@noreply.github.com> 
CC: "IT IS AG" <odoo@itis.de>, "Mention" <mention@noreply.github.com> 
Gesendet: Montag, 9. September 2019 17:31:21 
Betreff: Re: [OCA/data-protection] Checkin ITIS Odoo 12 GDPDR Modules (#34) 


Hey @ITISAG , thank you for your Pull Request. 
It looks like some users haven't signed our C ontributor L icense A greement, yet. 
You can read and sign our full Contributor License Agreement here: http://odoo-community.org/page/cla 
Here is a list of the users: 

    * Christopher Lorenz christopherl2@itis.de (no github login found) 

Appreciation of efforts, 
OCA CLAbot

**Comment by etobella** [comment]
Commits have not been preserved, so you have not followed the standard migration.

**Comment by pedrobaeza** [comment]
@ITISAG the bot is automatic, so although the company CLA is signed, you must indicate which GitHub logins must be included under that company CLA.

And mentioning the sponsorship here is totally out of scope IMO.

**Comment by OSevangelist** [comment]
Dear @ITISAG i think our Bot, @etobella and @pedrobaeza are perfectly right on the matter. I did a similar mistake in porting a module from v11 to v12 in 

https://github.com/OCA/l10n-germany/pull/56

I think it is very important that we follow the quality rules. I am very thankful for senior OCA contributors as @pedrobaeza to reinforce this. So please be so kind an follow the indicated link while porting the module. I will have to do the same with my pull request ;-)

**Comment by ITISAG** [comment]
Pedro, it is the second time that we run into this pseudo legal nonsense. Pls read the contributors agreement and you will find that there is absolutely no obligation to put inviduals of a company into the public. 


Bit maybe you help me understand how comes that OCA still cannot distingush between a company and a invidual contributing and force people to have a personal github account, which they even don't want (or do you want us all to be assimilated as an Microsft employee using this tainted platform?) 


There is one thing to have errors in the code, which we are very happy to fix, the other is to hinder people to contribute with a misaligned technical circumstance and not legally backed process on intellectual property - friends! This is why I am embarrassed! 


And @Fred: yes, we are going to review for sure, but we are not willing to support bot nonsense. 





----- Ursprüngliche Mail -----

Von: "Pedro M. Baeza" <notifications@github.com> 
An: "OCA/data-protection" <data-protection@noreply.github.com> 
CC: "IT IS AG" <odoo@itis.de>, "Mention" <mention@noreply.github.com> 
Gesendet: Montag, 9. September 2019 20:03:04 
Betreff: Re: [OCA/data-protection] Checkin ITIS Odoo 12 GDPDR Modules (#34) 


@ITISAG the bot is automatic, so although the company CLA is signed, you must indicate which GitHub logins must be included under that company CLA. 
And mentioning the sponsorship here is totally out of scope IMO.

**Comment by pedrobaeza** [comment]
@ITISAG (whoever is behind this alias - I suppose Joerg), if you would take the seconds to check at least the message issued by the bot, you will find that the problem is that the commit was done by Christopher Lorenz with the email christopherl2@itis.de, which is not even linked to any GitHub user. And so, we can't check that it belongs to a valid CLA covered contact. The bot is not covering any email address at an specific domain under ICLA (this has been discussed other times and there are strong reasons for not to do it). And so, the bot is going to complain each time you do the same with unknown addresses, which is the case.

But the solution is simple: write to cla@odoo-community.org, saying that this email address is also covered by ITIS ICLA, and our delightful secretary will add it without any problem. A link to a GitHub user is still needed to check permission and other stuff though.

Said that, your unrespectful behavior makes me tell you that this is the last time I'm going to answer you unless you change your attitude. Your sponsorship is not paying my time (my work is voluntary), and even if so, I deserve other kind of answers, as I always try to help you.

**Comment by rafaelbn** [comment]
Hi @ITISAG you could be interested in https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst . From there you can go to the Wiki Migration,

**Pull request closed without merging**
