### PR TITLE
[13.0][FIX] privacy consent function not recordset-aware

### PR DESCRIPTION
**Pull request by sergiocorato**

### CODE REVIEW

**Review by yajo — APPROVED** [review]

**Comment by yajo** [comment]
Fast-forwarding fw port from #51.

/ocabot merge patch

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Ouch, Travis is red. Can you check?

**Comment by sergiocorato** [comment]
Sorry, I haven't run pre-commit, I fix it

**Review by marcelsavegnago — APPROVED** [review]

**Pull request merged**
