### PR TITLE
[16.0][IMP] privacy_consent: use consteq, add some security tests

### PR DESCRIPTION
**Pull request by tde-banana-odoo**
Add some security-related tests

Use consteq for tokens comparison to lessen potential attacks using timing

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I suppose this one supersedes #71, isn't it? Please ping when ready to be reviewed.

**Comment by tde-banana-odoo** [comment]
Hello,

Indeed, waiting for https://github.com/OCA/data-protection/pull/71 to be merged. This one just adds some new commits. I will ping and set to "ready for review" once ready, that's why it is still in draft :) .

Cheers !

**Comment by pedrobaeza** [comment]
You can rebase over #74 to get green pre-commit.

**Comment by tde-banana-odoo** [comment]
Hello,

Thanks, rebased :) small PR ready for review then :) .

**Review by pedrobaeza — APPROVED** [review]
Thank you very much for these improvements

/ocabot merge patch

**Pull request merged**
