### PR TITLE
[14.0][MIG] privacy_consent: Migration to 14.0

### PR DESCRIPTION
**Pull request by victoralmau**
Superseed: https://github.com/OCA/data-protection/pull/56

Locked by: 
- [x] `privacy` https://github.com/OCA/data-protection/pull/60

Migration to 14.0

Please @Yajo and @joao-p-marques can you review it?

@Tecnativa TT31810

### CODE REVIEW

**Review by joao-p-marques — APPROVED** [review]
Code review

**Comment by yajo** [comment]
Please rebase, #60 is merged now.

**Comment by dreispt** [comment]
Superseded by #56

**Comment by pedrobaeza** [comment]
In fact, this one supersedes the other, that is red. Can you please check and reopen?

**Comment by dreispt** [comment]
Sure, my mistake.

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
