### PR TITLE
[MIG] privacy: migration to 16.0

### PR DESCRIPTION
**Pull request by tde-banana-odoo**

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
@pedrobaeza Looking at the doc, I merged two translations commits (a pot file update, and an automatic po file update). I kept the author-based translations. Not sure if I should merge "[UPD] update translations" and [UPD] Readme" into a single administrative commit ? As those are separate things.

Edit: seems there are still 2 translations commits in history, one for 12 and one for 14, should I merge them ?

**Comment by pedrobaeza** [comment]
Let's keep it, for not going too further...

**Review by pedrobaeza — APPROVED** [review]
Although some changes (manifest version and XML data) should be on the second commit, let's approve it for not being nitpicking.

**Review by wtaferner — APPROVED** [review]

**Comment by tde-banana-odoo** [comment]
Woop woop, my first PR in OCA :D .

**Comment by pedrobaeza** [comment]
Congratulations! I hope it won't be the last.

**Comment by jco-odoo** [comment]
@tde-banana-odoo We could add a portal such that the portal users can see their data processing activities automatically.

**Pull request merged**
